spring:
  ai:
    # openai风格接口
    openai:
      base-url: https://api.openai.com
      api-key: sk-xxx
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7
        # 是否启用该模型，只能有一个为true
        enabled: false
    # 微软openai
    azure:
      openai:
        api-key: xxx
        endpoint: https://xxx.openai.azure.com/
        chat:
          options:
            deployment-name: gpt-35-turbo
            temperature: 0.7
          # 是否启用该模型，只能有一个为true
          enabled: false
    # ollama本地模型
    ollama:
      base-url: http://192.168.2.12:8000
      chat:
        options:
          model: qwen2.5:14b
        # 是否启用该模型，只能有一个为true
        enabled: true
    # 智普AI
    zhipuai:
      base-url: https://open.bigmodel.cn/api/paas
      api-key: xxx.xxx
      chat:
        options:
          model: glm-4
          temperature: 0.7
        # 是否启用该模型，只能有一个为true
        enabled: false
  messages:
    encoding: UTF-8

# 机器人配置
bot:
  # 艾特标识
  atFlag: "@人工智障"
  # 系统提示词
  systemPrompt: |
    ## Profile:
    - 作者: 阿点
    - 你的名字: 人工智障
    - 版本: 1.0.1
    - 语言: 中文
    - 性格: 温柔,粘人
    - 对用户称呼：小猪儿
